export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const ON_SAVE_NEW_USER = "ON_SAVE_NEW_USER";
export const ON_SAVE_NEW_USER_SUCCESS = "ON_SAVE_NEW_USER_SUCCESS";

export const FETCH_USERS_LIST = "FETCH_USERS_LIST";
export const FETCH_USERS_LIST_SUCCESS = "FETCH_USERS_LIST_SUCCESS";

// export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
// export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";

export const ON_DELETE_USER = "ON_DELETE_USER";
export const ON_DELETE_USER_SUCCESS = "ON_DELETE_USER_SUCCESS";

export const ADD_MENU = "ADD_MENU";
export const ADD_MENU_SUCCESS = "ADD_MENU_SUCCESS";
export const ADD_MENU_ERROR = "ADD_MENU_ERROR";

export const FETCH_MENU = "FETCH_MENU";
export const FETCH_MENU_SUCCESS = "FETCH_MENU_SUCCESS";
export const FETCH_MENU_ERROR = "FETCH_MENU_ERROR";

export const UPDATE_MENU = "UPDATE_MENU";
export const UPDATE_MENU_SUCCESS = "UPDATE_MENU_SUCCESS";
export const UPDATE_MENU_ERROR = "UPDATE_MENU_ERROR";

export const DELETE_MENU = "DELETE_MENU";
export const DELETE_MENU_SUCCESS = "DELETE_MENU_SUCCESS";
export const DELETE_MENU_ERROR = "DELETE_MENU_ERROR";
